### ISSUE TITLE
scss organization

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/styleguide-starterpack#1]
what do you think about having all our styleguide scss in it's own directory to seperate from breadpudding base stuff.

more isolation I suppose

**Comment by luetkemj** [comment]
Doing it

**Comment by streeetlamp** [comment]
![fv8w0tb jpg](https://cloud.githubusercontent.com/assets/1740634/5905737/425a0e1e-a560-11e4-931d-6c4f7c7bbc0f.gif)
